DATA:
    ROOT: '/root/auto-fs/videos/'
    TRAIN_FILE: 'datasets_splits/hmdb_splits/test_train.txt'
    VAL_FILE: 'datasets_splits/hmdb_splits/test_val.txt'
    DATASET: hmdb51
    NUM_FRAMES: 32
    NUM_CLASSES: 51
    LABEL_LIST: 'labels/hmdb_51_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-04
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 10
